package project.controller.duel.CardEffects.MonsterEffectEnums;

public enum UponSummoningEffect {
    SET_ATK_1900_IF_NORMAL_SUMMONED,
    SET_ATK_1900_IF_SET,
    DESTROY_ALL_OF_YOUR_OPPONENTS_CARDS,
    IF_NORMAL_SUMMONED_SPECIAL_SUMMON_1_LEVEL_4_OR_LESS_NORMAL_MONSTER_FROM_HAND_IN_DEFENSE_POSITION,
}
