package CardEffects.SpellEffectEnums;

public enum LogicalActivationRequirement {
    MUST_EXIST_AT_LEAST_1_MONSTER_IN_EITHER_GY,
    OWNER_MUST_CONTROL_DARK_MONSTER,
    OWNER_MUST_CONTROL_WARRIOR_MONSTER,
    OWNER_MUST_HAVE_ONE_SPELL_FIELD_CARD_IN_DECK,
    OPPONENT_MUST_CONTROL_AT_LEAST_1_MONSTER,
    OWNER_MUST_HAVE_AT_LEAST_ONE_CARD_IN_HAND,
    TRAP_CARD_INFLICTING_DAMAGE_MUST_BE_ACTIVATED,
    SPELL_FIELD_CARD_CANNOT_BE_ACTIVATED_ON_TURN_CLOSED_FOREST_WAS_DESTROYED,
    OWNER_MUST_HAVE_RITUAL_MONSTER_IN_HAND,
    OWNER_MUST_HAVE_CARDS_WITH_SUM_OF_LEVELS_AT_LEAST_RITUAL_MONSTERS_LEVEL_IN_DECK,
}
