package CardEffects.SpellEffectEnums;

public enum UserReplyForActivation {
    CHOOSE_ONE_DARK_MONSTER_OWNER_CONTROLS,
    CHOOSE_ONE_WARRIOR_MONSTER_OWNER_CONTROLS,
    CHOOSE_ONE_MONSTER_OWNER_CONTROLS,
    CHOOSE_ONE_MONSTER_FROM_EITHER_GY,
    CHOOSE_ONE_OF_OPPONENTS_MONSTERS,
    CHOOSE_ONE_SPELL_FIELD_CARD_FROM_OWNER_DECK,
    CHOOSE_UP_TO_TWO_SPELL_TRAP_CARDS_IN_FIELD,
    DISCARD_1_CARD,
}
