package controller.duel.CardEffects.TrapEffectEnums;

public enum MonsterAttackingTrapCardEffect {
    NEGATE_OPPONENT_ATTACK,
    INFLICT_DAMAGE_TO_OPPONENT_EQUAL_TO_MONSTERS_ATK,
    DESTROY_ALL_OPPONENT_ATTACK_POSITION_MONSTERS,
    END_BATTLE_PHASE,
    PAY_2000_LP,
    NEGATE_ACTIVATION_OR_SUMMONING_AND_DESTROY_CARD,
    SPECIAL_SUMMON_ONE_MONSTER_IN_YOUR_GRAVEYARD_IN_FACE_UP_ATTACK_POSITION,
}
