package controller.duel.CardEffects.SpellEffectEnums;

public enum FieldSpellEffect {
    FIEND_GAIN_200_ATK_DEF,
    SPELLCASTER_GAIN_200_ATK_DEF,
    FAIRY_LOSE_200_ATK_DEF,
    INSECT_GAIN_200_ATK_DEF,
    BEAST_GAIN_200_ATK_DEF,
    PLANT_GAIN_200_ATK_DEF,
    BEASTWARRIOR_GAIN_200_ATK_DEF,
    BEAST_MONSTERS_OWNER_CONTROLS_GAIN_100_ATK_FOR_EACH_MONSTER_IN_GY,
    FIELD_SPELL_CANT_BE_ACTIVATED_ON_TURN_THIS_IS_DESTROYED,
    WATER_GAINS_500_ATK,
    WATER_LOSES_400_DEF,
}
