package controller.duel.CardEffects.SpellEffectEnums;

public enum FieldSpellEffect {
    FIEND_GAIN_200_ATK_DEF,
    SPELLCASTER_GAIN_200_ATK_DEF,
    FAIRY_LOSE_200_ATK_DEF,
    INSECT_GAIN_200_ATK_DEF,
    BEAST_GAIN_200_ATK_DEF,
    BEASTWARRIOR_GAIN_200_ATK_DEF,
    BEAST_MONSTERS_OWNER_CONTROLS_GAIN_100_ATK_FOR_EACH_MONSTER_IN_GY,
    AQUA_GAINS_500_ATK,
    AQUA_LOSES_400_DEF,
}
