package controller.duel.CardEffects.SpellEffectEnums;

public enum NormalSpellCardEffect {
    SPECIAL_SUMMON_MONSTER_FROM_EITHER_GY,
    ADD_SPELL_FIELD_CARD_FROM_DECK_TO_HAND,
    DRAW_2_CARDS,
    DESTROY_ALL_OF_OPPONENTS_MONSTERS,
    CONTROL_ONE_OF_OPPONENTS_MONSTERS_UNTIL_END_PHASE,
    DESTROY_ALL_OF_OPPONENTS_SPELL_AND_TRAP_CARDS,
    DESTROY_ALL_MONSTERS_ON_THE_FIELD,
    FLIP_OPPONENT_MONSTER_CARDS,
}
