package controller.duel.CardEffects.SpellEffectEnums;

public enum UserReplyForActivation {
    CHOOSE_ONE_DARK_MONSTER_OWNER_CONTROLS,
    CHOOSE_ONE_WARRIOR_MONSTER_OWNER_CONTROLS,
    CHOOSE_ONE_MONSTER_OWNER_CONTROLS,
    CHOOSE_ONE_MONSTER_FROM_EITHER_GY,
    CHOOSE_ONE_OF_OPPONENTS_MONSTERS,
    CHOOSE_ONE_SPELL_FIELD_CARD_FROM_OWNER_DECK,
    CHOOSE_UP_TO_TWO_SPELL_TRAP_CARDS_IN_FIELD,
    DISCARD_1_CARD,
    CHOOSE_NORMAL_MONSTERS_FROM_YOUR_DECK_WITH_SUM_OF_LEVELS_EQUAL_TO_A_RITUAL_MONSTER_LEVEL,
    CHOOSE_ONE_RITUAL_MONSTER_FROM_YOUR_HAND_WITH_LEVEL_EQUAL_TO_SUM_OF_LEVELS_YOU_CHOSE,
    CHOOSE_FACE_UP_ATTACK_POSITION_OR_DEFENSE_POSITION_OF_YOUR_MONSTER,
}
