package model;

public enum AIActionType {
    ACTIVATE_EFFECT,
    ATTACK_1,
    ATTACK_2,
    ATTACK_3,
    ATTACK_4,
    ATTACK_5,
    ATTACK_DIRECTLY,
    NORMAL_SUMMON,
    FLIP_SUMMON,
    TRIBUTE_SUMMON,
    SPECIAL_SUMMON,
    SET,
    CHANGE_CARD_POSITION_TO_ATTACK,
    CHANGE_CARD_POSITION_TO_DEFENSE,
    NOTHING,
}
