package test.maven.model.card.cardEffects.SpellEffectEnums;

public enum ContinuousSpellCardEffect {
    FOR_3_TURNS_OPPONENT_CANT_ATTACK,
    IF_A_MONSTER_OWNER_CONTROLS_IS_DESTROYED_DRAW_1_CARD,
    IF_A_SPELL_IS_ACTIVATED_OWNER_GAINS_500_LIFEPOINTS,
    MONSTERS_WITH_1500_OR_LESS_ATK_CANT_ATTACK,
    STANDBY_PHASE_PAY_100_LP_OR_DESTROY_CARD,
}
