package test.maven.model.card.cardEffects.SpellEffectEnums;

public enum FieldSpellEffect {
    FIEND_SPELLCASTER_MONSTERS_GAIN_200_ATK_DEF_FAIRY_LOSE_200_ATK_DEF,
    INSECT_BEAST_PLANT_BEASTWARRIOR_GAIN_200_ATK_DEF,
    BEAST_MONSTERS_OWNER_CONTROLS_GAIN_100_ATK_FOR_EACH_MONSTER_IN_GY,
    FIELD_SPELL_CANT_BE_ACTIVATED_ON_TURN_THIS_IS_DESTROYED,
    WATER_GAINS_500_ATK_LOSE_400_DEF,
}
