package test.maven.model.card.cardEffects.MonsterEffectEnums;

public enum BeingAttackedEffect {
    NEITHER_PLAYER_RECEIVES_BATTLE_DAMAGE,
    CANNOT_BE_DESTROYED_BY_BATTLE,
    IF_FACE_DOWN_AT_THE_BEGINNING_THEN_OPPONENT_RECEIVES_1000_DAMAGE,
    NEGATE_ATTACK_ONCE_PER_TURN,
    SPECIAL_SUMMON_CYBERSE_NORMAL_MONSTER_FROM_HAND_GV_DECK,
}
