package project.model.SpellEffectEnums;

public enum NormalSpellCardEffect {
    SPECIAL_SUMMON_MONSTER_FROM_EITHER_GY,
    ADD_SPELL_FIELD_CARD_FROM_DECK_TO_HAND,
    DRAW_2_CARDS,
    DESTROY_ALL_OF_OPPONENTS_MONSTERS,
    CONTROL_ONE_OF_OPPONENTS_MONSTERS_UNTIL_END_PHASE,
    DESTROY_ALL_OF_OPPONENTS_SPELL_AND_TRAP_CARDS,
    DESTROY_ALL_MONSTERS_ON_THE_FIELD,
    FLIP_OPPONENT_MONSTER_CARDS,
    ALL_SPELL_TRAPS_IN_FIELD_GO_TO_RESPECTIVE_HANDS,
    SPECIAL_SUMMON_ONE_LEVEL_5_OR_HIGHER_NORMAL_MONSTER_FROM_YOUR_HAND,
    BOTH_PLAYERS_DISCARD_ALL_CARDS_FROM_HAND_AND_DRAW_CARDS_EQUAL_TO_THROWN_AWAY_CARDS,
}
