package project.model.SpellEffectEnums;

public enum QuickSpellEffect {
    DISCARD_1_CARD_THEN_TARGET_UP_TO_2_SPELL_CARDS_AND_DESTROY,
    TARGET_1_SPELL_TRAP_CARD_AND_DESTROY,
    TRAP_CARD_INFLICTING_DAMAGE_IS_ACTIVATED_SET_DAMAGE_OF_TRAP_CARD_TO_0,
    TARGET_FACE_UP_MONSTER_WILL_HAVE_HALF_ATTACK_UNTIL_THE_END_OF_THIS_TURN,
    TARGET_FACE_UP_MONSTER_WILL_GAIN_700_ATTACK_UNTIL_THE_END_OF_THIS_TURN,
}
