package project.model.TrapEffectEnums;

public enum NormalTrapCardEffect {
    SKIP_OPPONENT_DRAW_PHASE_NEXT_TURN,
    SPECIAL_SUMMON_ONE_MONSTER_IN_YOUR_GRAVEYARD_IN_FACE_UP_ATTACK_POSITION,
    OPPONENT_DISCARDS_ALL_CARDS_WITH_A_GIVEN_NAME_OTHERWISE_OWNER_LOSES_ONE_RANDOM_CARD,
    SELECT_2_SPELL_CARDS_FROM_OWNER_GRAVEYARD_AND_SHUFFLE_THEM_INTO_OWNER_DECK,
    DEAL_300_MULTIPLIED_BY_NUMBER_OF_CARDS_IN_GRAVEYARD_TO_OPPONENT,
    DESTROY_ALL_CARDS_IN_THE_SAME_COLUMN_AS_THIS_CARD,
}
