package CardData.General;

public enum RowOfCardLocation {
    ALLY_MONSTER_ZONE,
    ALLY_SPELL_ZONE,
    ALLY_SPELL_FIELD_ZONE,
    ALLY_HAND_ZONE,
    ALLY_DECK_ZONE,
    ALLY_GRAVEYARD_ZONE,
    OPPONENT_MONSTER_ZONE,
    OPPONENT_SPELL_ZONE,
    OPPONENT_SPELL_FIELD_ZONE,
    OPPONENT_HAND_ZONE,
    OPPONENT_DECK_ZONE,
    OPPONENT_GRAVEYARD_ZONE
}
