package project.model.aidata;

public enum AISpellTrapSelections {
    SELECT_A_SPECIAL_SUMMONING_TRAP_CARD_IN_BOARD,
    SELECT_A_MONSTER_DESTROYING_TRAP_CARD_IN_BOARD,
    SELECT_A_DAMAGE_INFLICTING_TRAP_CARD_IN_BOARD,
    SELECT_A_MONSTER_ATTACK_NEGATING_TRAP_CARD_IN_BOARD,
    NOTHING,
}
