package controller.duel.CardEffects.MonsterEffectEnums;

public enum BeingAttackedEffect {
    NEITHER_PLAYER_RECEIVES_BATTLE_DAMAGE,
    IF_DESTROYED_AND_SENT_TO_GRAVEYARD_SEND_ATTACKING_MONSTER_TO_GRAVEYARD,
    CANNOT_BE_DESTROYED_BY_BATTLE,
    IF_FACE_DOWN_AT_THE_BEGINNING_THEN_OPPONENT_RECEIVES_1000_DAMAGE,
    SET_ATTACKING_MONSTER_ATK_TO_0_ONCE_PER_TURN,
    NEGATE_ATTACK_ONCE_PER_TURN,
    SPECIAL_SUMMON_CYBERSE_NORMAL_MONSTER_FROM_HAND_GV_DECK_ONCE_PER_TURN,
}
