package controller.duel.CardEffects.MonsterEffectEnums;

public enum ContinuousMonsterEffect {
    ALL_ALLY_WARRIOR_MONSTERS_GAIN_400_ATK,
    CANNOT_BE_ATTACKED_IF_YOU_CONTROL_ANOTHER_MONSTER,
    ATK_IS_SET_300_MULTIPLIED_BY_TOTAL_OF_FACE_UP_MONSTER_LEVELS_YOU_CONTROL,
    OPPONENT_CANNOT_ACTIVATE_TRAP_CARDS_WHILE_THIS_CARD_IS_FACE_UP,
}
