package controller.duel.CardEffects.MonsterEffectEnums;

public enum SummoningRequirement {
    TRIBUTE_1_MONSTER,
    TRIBUTE_2_MONSTERS,
    TRIBUTE_3_MONSTERS,
    TRIBUTE_SPECIFIC_MONSTERS,
    DISCARD_1_CARD,
    TRIBUTE_MONSTERS_WITH_SUM_OF_LEVELS_AT_LEAST_THE_MONSTERS_LEVEL,
    MUST_USE_ADVANCED_RITUAL_SPELL,
    CAN_BE_NORMAL_SUMMONED,
    CAN_BE_TRIBUTE_SUMMONED,
    CAN_BE_SPECIAL_SUMMONED,
    CAN_BE_RITUAL_SUMMONED,
}
