package project.model.cardData.General;

public enum CardPosition {
    FACE_UP_ATTACK_POSITION,
    FACE_UP_DEFENSE_POSITION,
    FACE_UP_ACTIVATED_POSITION,
    FACE_DOWN_MONSTER_SET_POSITION,
    FACE_DOWN_SPELL_SET_POSITION,
    NOT_APPLICABLE,
}
